### ISSUE TITLE
Switch Icon Picker to Material Icons

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/B1App#52]
The icon picker for tabs in the admin still uses a font-awesome icon picker.  Find a material icon alternative.

**Comment by PhotoPaul** [comment]
Is there an easy way to extract the code from the official documentation?
https://mui.com/material-ui/material-icons/

Here is the code:
https://github.com/mui/material-ui/blob/master/docs/data/material/components/material-icons/SearchIcons.js
https://github.com/mui/material-ui/blob/master/docs/data/material/components/material-icons/synonyms.js

**Comment by jzongker** [comment]
This was completed a few weeks ago.  Just closing the ticket.
